name: Publish top-level plugin to pub.dev

on:
  push:
    tags:
      - 'pub-vietmap_flutter_plugin-[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1