name: Publish top-level plugin to pub.dev

on:
  push:
    tags:
      - 'pub-vietmap_flutter_plugin-[0-9]+.[0-9]+.[0-9]+*'

env:
    FLUTTER_CHANNEL: 'stable'
    FLUTTER_VERSION: '3.13.9'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    # uses: vietmap-company/vietmap_flutter_plugin/.github/workflows/publish.yml@main
    with:
        environment: pub.dev